// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZgJlOfjJzPTJv9rxHtxrAD8Xa8VW3B2E',
    appId: '1:347281117745:web:4f4a2e5eb26a4977b0fb10',
    messagingSenderId: '347281117745',
    projectId: 'chat-app-af1ec',
    authDomain: 'chat-app-af1ec.firebaseapp.com',
    storageBucket: 'chat-app-af1ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJw3XZPDt1UDUkBnQVZKMfFWRlB3MaJtk',
    appId: '1:347281117745:android:f390310b7c61baccb0fb10',
    messagingSenderId: '347281117745',
    projectId: 'chat-app-af1ec',
    storageBucket: 'chat-app-af1ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbjbU-aDNsbJJOMthHeaP3PGwsS5BCcL0',
    appId: '1:347281117745:ios:6e3c8615160b2574b0fb10',
    messagingSenderId: '347281117745',
    projectId: 'chat-app-af1ec',
    storageBucket: 'chat-app-af1ec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
